apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: manish332000/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    # - image: manish332000/event-bus
    #   context: event-bus
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - dest: .
    #         src: "*.js"
    # - image: manish332000/moderation
    #   context: moderation
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - dest: .
    #         src: "*.js"
    # - image: manish332000/posts
    #   context: posts
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - dest: .
    #         src: "*.js"
    # - image: manish332000/query
    #   context: query
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - dest: .
    #         src: "*.js"
manifests:
  rawYaml:
    - infra/k8/auth-depl.yaml
    # - infra/k8s/client-depl.yaml
    # - infra/k8s/comments-depl.yaml
    # - infra/k8s/event-bus-depl.yaml
    # - infra/k8s/ingress-srv.yaml
    # - infra/k8s/moderation-depl.yaml
    # - infra/k8s/posts-depl.yaml
    # - infra/k8s/posts-serv.yaml
    # - infra/k8s/query-depl.yaml
