apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: manish332000/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
manifests:
  rawYaml:
    - infra/k8/*
