apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ticketing
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-419006
  artifacts:
    - image: us.gcr.io/ticketing-dev-419006/ticketing_auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: us.gcr.io/ticketing-dev-419006/ticketing_client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: us.gcr.io/ticketing-dev-419006/ticketing_ticket
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: us.gcr.io/ticketing-dev-419006/ticketing_orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: us.gcr.io/ticketing-dev-419006/ticketing_expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8/*
